In [1]:
import cv2
import tensorflow as tf

import json

# load class
with open("../faster_rcnn_resnet152_v1_640x640_1/mscoco_complete_label_map.json") as file:
    c = json.load(file)

classes = []
for i in c:
    classes.append(i["item"]["display_name"])


# load model
MODEL_PATH = "../faster_rcnn_resnet152_v1_640x640_1"
model = tf.saved_model.load(MODEL_PATH)

2023-04-18 23:03:55.371616: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
cap = cv2.VideoCapture(0)
ret, frame = cap.read()


In [7]:
rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

In [8]:
input_frame = tf.expand_dims(rgb_frame, axis=0)
input_frame = tf.image.resize(input_frame, (640, 640))
input_frame = tf.cast(input_frame, dtype=tf.uint8)

In [9]:
detections = model(input_frame)
boxes = detections['detection_boxes'][0].numpy()
class_ids = detections['detection_classes'][0].numpy().astype(int)
scores = detections['detection_scores'][0].numpy()

2023-04-17 14:53:10.753407: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'input_tensor' with dtype uint8 and shape [1,?,?,3]
	 [[{{node input_tensor}}]]


In [10]:
print("boxes", detections['detection_boxes'])
print("classes", detections['detection_classes'])
print("scores", detections['detection_scores'])

boxes tf.Tensor(
[[[0.05377436 0.01439104 0.90105355 0.3665305 ]
  [0.07231774 0.02220182 0.67127156 0.47486115]
  [0.10547023 0.01312671 0.91670495 0.24186817]
  ...
  [0.9614436  0.19141388 0.98383135 0.23716998]
  [0.2614104  0.98246604 0.39513656 0.9969907 ]
  [0.6781097  0.9788753  0.82553387 0.996651  ]]], shape=(1, 300, 4), dtype=float32)
classes tf.Tensor(
[[17. 17. 17. 35. 85. 85. 85.  3.  1. 17. 77. 84.  3.  1. 17. 84. 17. 17.
  85. 17. 17. 77. 84. 85. 85. 72. 82. 84. 85. 85.  3.  3. 84. 17. 85. 17.
  85.  3.  6. 17. 17. 77. 17.  3.  3.  3. 18. 17.  1. 17. 17.  3. 84. 73.
  85. 15.  3.  6.  3. 17.  3. 39. 85. 85. 36. 72. 10. 17. 82.  3.  1. 77.
  85. 17. 84. 72. 85.  3.  7. 15. 72. 85. 17. 47. 15. 76. 72. 17. 85.  1.
  15. 76.  1. 85. 17. 76.  6. 17. 85. 15. 76. 73. 17. 76.  3. 47. 10. 84.
  72. 15.  3.  6.  1. 84. 47. 17.  1. 17. 17. 82. 15. 73. 82.  3.  3.  3.
  18.  3.  3.  3. 17.  6. 72. 84. 72. 85. 15. 17. 72.  6. 72. 16. 16. 84.
  84.  3. 73. 82. 17. 17. 15. 85.  3. 85.

In [14]:
print("boxes[0]", detections['detection_boxes'][0])
print("classes[0]", detections['detection_classes'][0])
print("scores[0]", detections['detection_scores'][0])

boxes[0] tf.Tensor(
[[0.05377436 0.01439104 0.90105355 0.3665305 ]
 [0.07231774 0.02220182 0.67127156 0.47486115]
 [0.10547023 0.01312671 0.91670495 0.24186817]
 ...
 [0.9614436  0.19141388 0.98383135 0.23716998]
 [0.2614104  0.98246604 0.39513656 0.9969907 ]
 [0.6781097  0.9788753  0.82553387 0.996651  ]], shape=(300, 4), dtype=float32)
classes[0] tf.Tensor(
[17. 17. 17. 35. 85. 85. 85.  3.  1. 17. 77. 84.  3.  1. 17. 84. 17. 17.
 85. 17. 17. 77. 84. 85. 85. 72. 82. 84. 85. 85.  3.  3. 84. 17. 85. 17.
 85.  3.  6. 17. 17. 77. 17.  3.  3.  3. 18. 17.  1. 17. 17.  3. 84. 73.
 85. 15.  3.  6.  3. 17.  3. 39. 85. 85. 36. 72. 10. 17. 82.  3.  1. 77.
 85. 17. 84. 72. 85.  3.  7. 15. 72. 85. 17. 47. 15. 76. 72. 17. 85.  1.
 15. 76.  1. 85. 17. 76.  6. 17. 85. 15. 76. 73. 17. 76.  3. 47. 10. 84.
 72. 15.  3.  6.  1. 84. 47. 17.  1. 17. 17. 82. 15. 73. 82.  3.  3.  3.
 18.  3.  3.  3. 17.  6. 72. 84. 72. 85. 15. 17. 72.  6. 72. 16. 16. 84.
 84.  3. 73. 82. 17. 17. 15. 85.  3. 85. 60. 85. 72.  

In [12]:
print("boxes[0]", detections['detection_boxes'][0].numpy())
print("classes[0]", detections['detection_classes'][0].numpy().astype(int))
print("scores[0]", detections['detection_scores'][0].numpy())

boxes[0] [[0.05377436 0.01439104 0.90105355 0.3665305 ]
 [0.07231774 0.02220182 0.67127156 0.47486115]
 [0.10547023 0.01312671 0.91670495 0.24186817]
 ...
 [0.9614436  0.19141388 0.98383135 0.23716998]
 [0.2614104  0.98246604 0.39513656 0.9969907 ]
 [0.6781097  0.9788753  0.82553387 0.996651  ]]
classes[0] [17 17 17 35 85 85 85  3  1 17 77 84  3  1 17 84 17 17 85 17 17 77 84 85
 85 72 82 84 85 85  3  3 84 17 85 17 85  3  6 17 17 77 17  3  3  3 18 17
  1 17 17  3 84 73 85 15  3  6  3 17  3 39 85 85 36 72 10 17 82  3  1 77
 85 17 84 72 85  3  7 15 72 85 17 47 15 76 72 17 85  1 15 76  1 85 17 76
  6 17 85 15 76 73 17 76  3 47 10 84 72 15  3  6  1 84 47 17  1 17 17 82
 15 73 82  3  3  3 18  3  3  3 17  6 72 84 72 85 15 17 72  6 72 16 16 84
 84  3 73 82 17 17 15 85  3 85 60 85 72  3  3 10  3 35 85  6 18 77 17 17
 10 43  3 82  3  6 84 85 76 15 60 77 76 84  3 62 10 10 84 73 72 73 10 65
 84 18  3  1  3 17 72 85 10  3 18  1  3  3 15 62  3 72  3 62 17  6 60 73
 17  6 15 72  6  3  5 17 15 35 84 4